variables:
  TIER: none
  STAGE: none

cache:
  paths:
    - node_modules/

default:
  before_script:
    - yarn --frozen-lockfile

stages:
  - quality
  - publish

version:
  stage: quality
  only:
    - external_pull_requests
  except:
    - master
  script:
    - echo ""

lint:
  stage: quality
  only:
    - external_pull_requests
    - master
  script:
    - echo ""

test:
  stage: quality
  only:
    - external_pull_requests
    - master
  script:
    - echo ""

format:
  stage: quality
  only:
    - external_pull_requests
    - master
  script:
    - echo ""

docker:
  stage: publish
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  before_script:
    - echo ""
  only:
    - master
  tags:
    - docker
  script:
    - echo ""

publish:
  stage: publish
  only:
    - master
  script:
    - echo ""
